name: kipoi-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - pkgconfig
  - conda-forge::hdf5
  - pip:
    - git+https://github.com/kipoi/kipoi.git #TODO: Add back when kipoi when py3.10 version is available
