name: Build, test and push images on demand

# Controls when the action will run. 
on: 
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buildtestandpush:
    # The type of runner that the job will run on
    strategy:
      fail-fast: true
      matrix:
        image: ["sharedpy3keras1.2", "mpra-dragonn", "extended_coda", "mmsplice",
        "mmsplice-mtsplice", "deepmel", "framepool", "kipoisplice", "deeptarget",
        "attentivechrome", "bpnet-oskn", "seqvec", "deepflybrain", "aparent-site_probabilities", 
        "aparent-veff"]
    runs-on: ubuntu-latest
    env:
      SINGULARITY_PULL_FOLDER: "/home/runner/singularity/"
      ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODOACCESSTOKEN }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install conda environment py39
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: py39
        environment-file: environment.ubuntu.singularity.yml
        python-version: 3.9
        auto-activate-base: false
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        mkdir -p /home/runner/singularity/
        sudo apt-get update && sudo apt-get install -y libhdf5-serial-dev pkg-config
        python -m pip install --upgrade pip
        pip install -e .
    - name: Build and test ${{ matrix.image }}
      shell: bash -l {0}
      run: |
        docker build -f dockerfiles/Dockerfile.kipoi-base-env -t kipoi/kipoi-docker:kipoi-base-env . 
        docker build -f dockerfiles/Dockerfile.${{ matrix.image }} -t kipoi/kipoi-docker:${{ matrix.image }} . 
        pytest -s test-containers/test_containers_from_command_line.py --image=kipoi/kipoi-docker:${{ matrix.image }} 
    - name: Push ${{ matrix.image }}
      shell: bash -l {0}
      if: ${{ success() }}
      run: |
        docker login --username ${{ secrets.DOCKERUSERNAME }} --password ${{ secrets.DOCKERPASSWORD }}
        docker push kipoi/kipoi-docker:${{ matrix.image }} 
        docker system prune -a -f
    - name: Update the singularity version of ${{ matrix.image }}
      shell: bash -l {0}
      if: ${{ success() }}
      run: |
        update_all_singularity ${{ matrix.image }} 

  buildandtestsharedpy3keras2:
    # The type of runner that the job will run on
    strategy:
      fail-fast: true
      matrix:
        modelgroup: ["Basenji,Basset,HAL,DeepSEA,Optimus_5Prime,labranchor,CleTimer,SiSp,FactorNet,MaxEntScan,pwm_HOCOMOCO",
          "DeepBind", "lsgkm-SVM", "rbp_eclip", "Xpresso"]
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Build and test sharedpy3keras2 with ${{ matrix.modelgroup }}
      run: |
        docker build -f dockerfiles/Dockerfile.kipoi-base-env -t kipoi/kipoi-docker:kipoi-base-env . 
        docker build -f dockerfiles/Dockerfile.sharedpy3keras2 -t kipoi/kipoi-docker:sharedpy3keras2 . 
        pytest -s test-containers/test_containers_from_command_line.py --image=kipoi/kipoi-docker:sharedpy3keras2 --modelgroup=${{ matrix.modelgroup }}


  buildandpushkipoibaseenvandsharedpy3keras2:
    needs: [buildandtestsharedpy3keras2, buildtestandpush]
      # The type of runner that the job will run on
    runs-on: ubuntu-latest
      # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Build sharedpy3keras2 and kipoi-base-env
      run: |
        docker build -f dockerfiles/Dockerfile.kipoi-base-env -t kipoi/kipoi-docker:kipoi-base-env . 
        docker build -f dockerfiles/Dockerfile.sharedpy3keras2 -t kipoi/kipoi-docker:sharedpy3keras2 . 
    - name: Push kipoi-base-env and sharedpy3keras2
      if: ${{ success() }}
      run: |
        docker login --username ${{ secrets.DOCKERUSERNAME }} --password ${{ secrets.DOCKERPASSWORD }}
        docker push kipoi/kipoi-docker:kipoi-base-env
        docker push kipoi/kipoi-docker:sharedpy3keras2
        docker system prune -a -f
