name:  Sync with https://github.com/kipoi/models

# Controls when the action will run. 
on:
  schedule:
  # Triggers the workflow once a month
  - cron: "0 9 1 * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buildtestandpush:
    # The type of runner that the job will run on
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUBPAT }}
      DOCKER_USERNAME: ${{ secrets.DOCKERUSERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERPASSWORD }}
      ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODOACCESSTOKEN }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install conda dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: py39
        environment-file: environment.ubuntu.singularity.yml
        python-version: 3.9
        auto-activate-base: false
    - name: Install pip dependencies
      shell: bash -l {0}
      run: |
        sudo apt-get update && sudo apt-get install -y libhdf5-serial-dev pkg-config
        python -m pip install --upgrade pip
        pip install -e .
    - name: Sync with kipoi model repo
      shell: bash -l {0}
      run: |
        python kipoi_containers/updateoradd.py
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
            token: ${{ secrets.GITHUBPAT }}
