name:  Sync with https://github.com/kipoi/models

# Controls when the action will run. 
on:
  repository_dispatch:
    types: [sync]
    
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buildtestandpush:
    # The type of runner that the job will run on
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUBPAT }}
      DOCKER_USERNAME: ${{ secrets.DOCKERUSERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERPASSWORD }}
      ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODOACCESSTOKEN }}
      SINGULARITY_PULL_FOLDER: "/home/runner/singularity/"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' 
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.8
    - name: Fetch system level dependencies
      run: sudo apt-get -q update && sudo apt-get install -y build-essential squashfs-tools
        libseccomp-dev cryptsetup libhdf5-serial-dev pkg-config
    - name: Build and install Apptainer
      run: |
        export VERSION=1.0.1 && \
        wget https://github.com/apptainer/apptainer/releases/download/v${VERSION}/apptainer-${VERSION}.tar.gz && \
        tar -xzf apptainer-${VERSION}.tar.gz && \
        cd apptainer-${VERSION}
        ./mconfig -v -p /usr/local
        make -C ./builddir all && sudo make -C ./builddir install
    - name: Install pip dependencies
      shell: bash -l {0}
      run: |
        mkdir -p /home/runner/singularity/
        sudo apt-get update && sudo apt-get install -y libhdf5-serial-dev pkg-config
        python -m pip install --upgrade pip
        pip install .
    - name: Sync with kipoi model repo
      shell: bash -l {0}
      run: |
        python kipoi_containers/updateoradd.py
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
            token: ${{ secrets.GITHUBPAT }}
